DROP TABLE TB_PRODUCT;
CREATE TABLE TB_PRODUCT(
    PRODUCT_TYPE VARCHAR2(93) NOT NULL,
    PRODUCT_SERIAL_NUMBER VARCHAR2(6) PRIMARY KEY,
    PRODUCT_PRICE NUMBER DEFAULT 0,
    PRODUCT_STOCK NUMBER DEFAULT 0
);
SELECT * FROM TB_PRODUCT;

DROP SEQUENCE SEQ_LEGO;
CREATE SEQUENCE SEQ_LEGO;
DROP SEQUENCE SEQ_ROBOT;
CREATE SEQUENCE SEQ_ROBOT;

INSERT INTO TB_PRODUCT VALUES ('LEGO', 'LG' || SEQ_LEGO.NEXTVAL, 55000, 100);
INSERT INTO TB_PRODUCT VALUES ('ROBOT', 'RB' || SEQ_ROBOT.NEXTVAL, 47000, 100);

DROP TABLE TB_PURCHASE;
CREATE TABLE TB_PURCHASE(
    CUSTOMER_ID VARCHAR2(15) REFERENCES TB_CUSTOMER(CUSTOMER_ID) ON DELETE SET NULL,
    CUSTOMER_PHONE VARCHAR2(11),
    PRODUCT_SERIAL_NUMBER VARCHAR2(6) REFERENCES TB_PRODUCT(PRODUCT_SERIAL_NUMBER) ON DELETE CASCADE,
    BUYING_NUMBER NUMBER DEFAULT 0,
    PAID_PRICE NUMBER
);

DROP TABLE TB_CUSTOMER;
CREATE TABLE TB_CUSTOMER(
    CUSTOMER_ID VARCHAR2(15) PRIMARY KEY,
    CUSTOMER_PASSWORD VARCHAR2(30),
    CUSTOMER_NAME VARCHAR2(20),
    CUSTOMER_PHONE VARCHAR2(11)
);
INSERT INTO TB_CUSTOMER VALUES('user01', 'pass01', 'name', 01012345678);

DROP TABLE TB_RIVIEW;
CREATE TABLE TB_RIVIEW(
    PRODUCT_SERIAL_NUMBER VARCHAR2(6) REFERENCES TB_PRODUCT(PRODUCT_SERIAL_NUMBER) ON DELETE CASCADE,
    CUSTOMER_ID VARCHAR2(15) REFERENCES TB_CUSTOMER(CUSTOMER_ID) ON DELETE SET NULL,
    REVIEW VARCHAR2(300)
);
COMMIT;