CREATE TABLE TB_ORDER(
    NAME VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(13) NOT NULL, 
    ADDRESS VARCHAR2(200) NOT NULL,
    REQUEST VARCHAR2(200),
    SANDWICH VARCHAR2(100) NOT NULL,
    VEGETABLE VARCHAR2(100),
    SAUCE VARCHAR2(300),
    COOKIE VARCHAR2(50),
    PAYMENT VARCHAR2(20),
    ORDER_DATE DATE DEFAULT SYSDATE
);

COMMIT;

SELECT * FROM TB_ORDER;